### ISSUE TITLE
Editor side became white in latest update 1.1.0

### ISSUE THREAD

**Issue by burakomer** [elliotwaite/jetbrains-godot-theme#5]
<img width="1686" alt="Screenshot 2023-12-05 at 09 54 56" src="https://github.com/elliotwaite/jetbrains-godot-theme/assets/44806700/90f99cb2-7fd1-45b0-985a-c2802dc50b86">

Jetbrains Rider version: 2023.2.3

I uninstalled and installed the theme, restarted the IDE, no luck.

**Comment by elliotwaite** [comment]
When you go to `Settings > Appearance & Behavior > Appearance > Theme` is "Godot Theme" selected as the theme?

**Comment by rymdkapten** [comment]
I have the same issue. Came after I updated to 1.1.0. 
The main editor has a styling which is similar to the built-in Light theme, with the exception that some parts are bold.

Checked "Settings > Appearance & Behavior > Appearance > Theme" and it is set to "Godot Theme".
No overrides active or other theme-modifying plugins installed. Tried other themes and they work normally. 

Same issue in both JetBrains Classic UI and New UI.

**Comment by elliotwaite** [comment]
When you go to `Settings > Editor > Color Scheme > Scheme`, is it also set to "Godot Theme"?

**Comment by rymdkapten** [comment]
No, that was set to "Classic Light". Switched to "Godot Theme" and it works!

Was curious to test if it was me who selected it by accident at some point so I tried reinstalling the theme.
Seems like it is set to "Classic Light" after installation and has to be configured manually. Perhaps this can be fixed somehow?

Either way, thanks for the help and the theme itself! I can finally code again! 😄

**Comment by elliotwaite** [comment]
Glad to hear that fixed it. I'm currently not sure why it would switch to the "Classic Light" color scheme when being reinstalled, but it's good to know about this issue, and maybe I'll figure out how to fix it in the future. I'm going to close this issue for now, since switching the color scheme manually is the only fix I know of, but feel free to comment more on this issue if anyone has suggestions for other ways to fix this.
